<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6LGQ6RF" failures="1" tests="6" name="demo.advanced.tests.DemoTests" time="25.517" errors="0" timestamp="2022-11-25T15:46:12 IST" skipped="3">
  <testcase classname="demo.advanced.tests.DemoTests" name="ATest2" time="1.996">
    <skipped/>
  </testcase> <!-- ATest2 -->
  <system-out/>
  <testcase classname="demo.advanced.tests.DemoTests" name="ATest2" time="1.340">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at demo.advanced.tests.DemoTests.ATest2(DemoTests.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- ATest2 -->
  <system-out/>
  <testcase classname="demo.advanced.tests.DemoTests" name="ATest2" time="1.745">
    <skipped/>
  </testcase> <!-- ATest2 -->
  <system-out/>
  <testcase classname="demo.advanced.tests.DemoTests" name="ATest2" time="6.816">
    <skipped/>
  </testcase> <!-- ATest2 -->
  <system-out/>
  <testcase classname="demo.advanced.tests.DemoTests" name="BTest3" time="6.757"/>
  <system-out/>
  <testcase classname="demo.advanced.tests.DemoTests" name="ZTest1" time="6.863"/>
  <system-out/>
</testsuite> <!-- demo.advanced.tests.DemoTests -->
